swagger: '2.0'
info:
  version: 1.0.0
  title: Your API
definitions:
  User:
    type: object
    properties:
      name:
        type: string
      age:
        type: integer
      occupation:
        type: string
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'






